name: cortex
description: a flutter project working as a client app for the cortex health system
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.4.0
  http: ^0.13.6
  image_picker: ^0.8.7+5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
  # Note of the creator of the font:
  # """
  # This font, created by Darrell Flood, is free to use for personal use (tho I appreciate donations!)
  # Please give as much as you honestly feel the font is worth to you.

  # For commercial use you must purchase a license by either:

  # 1. Paying me at least $20 via PayPal to dadiomouse@gmail.com
  # OR
  # 2. Buying a license here:
  # https://www.creativefabrica.com/product/martian-robotics/ref/74273/

  # Thank you for downloading this font and I hope you find a use for it!
  # """
    - family: Martian_robotics
      fonts:
        # - asset: fonts/Schyler-Regular.ttf
        - asset: assets/fonts/Martian Robotics Italic.ttf
          style: italic

